name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  web-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/web/package-lock.json'
          cache-directory: 'packages/web/node_modules'

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Run lint
        run: |
          cd web
          npm run lint:web

      - name: Run type check
        run: |
          cd web
          npm run typecheck:web

      - name: Run tests
        run: |
          cd web
          npm run test:web 